version: '3.3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    shm_size: 1gb
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  squid:
    build: 
      context: ./squid
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: postgres
      DB_PASS: ${POSTGRES_PASSWORD}
    volumes:
      - squid_data:/app/.squid
    command: ["npm", "run", "start"]
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  db_data:
  squid_data:

#  hasura:
#    image: hasura/graphql-engine:latest
#    ports:
#      - "3003:8080"
#    depends_on:
#      - db
#    environment:
#      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db:5432/squid
#      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
#      HASURA_GRAPHQL_DEV_MODE: "true"
#      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

#  frontend:
#    build: ../frontend
#    ports:
#      - "3003:3000"
#    depends_on:
#      - hasura

